import { Company } from "@/lib/types";

export const COMPANIES: Company[] = [
  // AI Infra (4)
  {
    id: "co_001",
    name: "OpenAI",
    url: "https://openai.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=OpenAI&backgroundColor=10a37f&textColor=ffffff",
    sector: "AI Infra",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2018,
    employees: "200-500",
    thesisScore: 92,
    tags: ["llm", "api-first", "enterprise"],
    lastSignalDate: "2026-02-15",
    description: "Large language models and AI platform for enterprise applications.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_002",
    name: "Anthropic",
    url: "https://anthropic.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Anthropic&backgroundColor=662d91&textColor=ffffff",
    sector: "AI Infra",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2021,
    employees: "50-200",
    thesisScore: 88,
    tags: ["ai-safety", "llm", "research"],
    lastSignalDate: "2026-02-10",
    description: "Constitutional AI and safe large language model development.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_003",
    name: "Mistral",
    url: "https://mistral.ai",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Mistral&backgroundColor=ff6b35&textColor=ffffff",
    sector: "AI Infra",
    stage: "Seed",
    hq: "Paris",
    founded: 2023,
    employees: "10-50",
    thesisScore: 85,
    tags: ["llm", "open-source", "inference"],
    lastSignalDate: "2026-01-28",
    description: "Open-source large language models for efficient inference.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_004",
    name: "Modal",
    url: "https://modal.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Modal&backgroundColor=4f46e5&textColor=ffffff",
    sector: "AI Infra",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2021,
    employees: "10-50",
    thesisScore: 82,
    tags: ["serverless", "gpu", "inference"],
    lastSignalDate: "2026-02-05",
    description: "Serverless GPU compute platform for AI applications.",
    enriched: undefined,
    noteIds: [],
  },

  // DevTools (4)
  {
    id: "co_005",
    name: "Linear",
    url: "https://linear.app",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Linear&backgroundColor=5e1bac&textColor=ffffff",
    sector: "DevTools",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2019,
    employees: "50-200",
    thesisScore: 91,
    tags: ["issue-tracking", "api-first", "plg"],
    lastSignalDate: "2026-02-12",
    description: "Fast, beautiful issue tracking for modern software teams.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_006",
    name: "Clerk",
    url: "https://clerk.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Clerk&backgroundColor=10b981&textColor=ffffff",
    sector: "DevTools",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2020,
    employees: "50-200",
    thesisScore: 87,
    tags: ["auth", "sdk", "developer-tools"],
    lastSignalDate: "2026-02-08",
    description: "Authentication and user management platform for developers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_007",
    name: "Resend",
    url: "https://resend.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Resend&backgroundColor=000000&textColor=ffffff",
    sector: "DevTools",
    stage: "Seed",
    hq: "San Francisco",
    founded: 2022,
    employees: "10-50",
    thesisScore: 84,
    tags: ["email", "api", "developer-tools"],
    lastSignalDate: "2026-02-03",
    description: "Email API for developers with beautiful templates.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_008",
    name: "Infisical",
    url: "https://infisical.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Infisical&backgroundColor=0099ff&textColor=ffffff",
    sector: "DevTools",
    stage: "Pre-seed",
    hq: "San Francisco",
    founded: 2023,
    employees: "1-10",
    thesisScore: 78,
    tags: ["secrets-management", "open-source", "security"],
    lastSignalDate: "2026-01-25",
    description: "Open-source secrets management platform for teams.",
    enriched: undefined,
    noteIds: [],
  },

  // FinTech (4)
  {
    id: "co_009",
    name: "Stripe",
    url: "https://stripe.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Stripe&backgroundColor=635bff&textColor=ffffff",
    sector: "FinTech",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2019,
    employees: "200-500",
    thesisScore: 94,
    tags: ["payments", "api-first", "enterprise"],
    lastSignalDate: "2026-02-14",
    description: "Global payment processing and financial infrastructure.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_010",
    name: "Wise",
    url: "https://wise.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Wise&backgroundColor=7d5a3b&textColor=ffffff",
    sector: "FinTech",
    stage: "Series A",
    hq: "London",
    founded: 2011,
    employees: "200-500",
    thesisScore: 89,
    tags: ["remittance", "payments", "cross-border"],
    lastSignalDate: "2026-02-09",
    description: "Fast, cheap international money transfers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_011",
    name: "Checkout.com",
    url: "https://checkout.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Checkout&backgroundColor=ff6b35&textColor=ffffff",
    sector: "FinTech",
    stage: "Series A",
    hq: "London",
    founded: 2012,
    employees: "50-200",
    thesisScore: 86,
    tags: ["payments", "api", "merchants"],
    lastSignalDate: "2026-02-01",
    description: "Unified payment processing for online merchants.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_012",
    name: "Plaid",
    url: "https://plaid.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Plaid&backgroundColor=00a8e1&textColor=ffffff",
    sector: "FinTech",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2013,
    employees: "50-200",
    thesisScore: 81,
    tags: ["banking-api", "data", "fintech"],
    lastSignalDate: "2026-01-30",
    description: "Bank connectivity API for financial applications.",
    enriched: undefined,
    noteIds: [],
  },

  // HealthTech (4)
  {
    id: "co_013",
    name: "Ro",
    url: "https://ro.co",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Ro&backgroundColor=ff4444&textColor=ffffff",
    sector: "HealthTech",
    stage: "Series A",
    hq: "New York",
    founded: 2017,
    employees: "50-200",
    thesisScore: 83,
    tags: ["telehealth", "prescription", "plg"],
    lastSignalDate: "2026-02-11",
    description: "Telehealth and prescription delivery platform.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_014",
    name: "Flatiron",
    url: "https://flatiron.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Flatiron&backgroundColor=009cde&textColor=ffffff",
    sector: "HealthTech",
    stage: "Series B",
    hq: "New York",
    founded: 2015,
    employees: "200-500",
    thesisScore: 88,
    tags: ["cancer", "software", "healthcare"],
    lastSignalDate: "2026-02-07",
    description: "Software platform for cancer treatment centers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_015",
    name: "Omada",
    url: "https://omada.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Omada&backgroundColor=1fa453&textColor=ffffff",
    sector: "HealthTech",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2017,
    employees: "200-500",
    thesisScore: 79,
    tags: ["chronic-disease", "digital-health", "b2b"],
    lastSignalDate: "2026-01-22",
    description: "Digital health platform for chronic disease management.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_016",
    name: "Tempus",
    url: "https://tempus.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Tempus&backgroundColor=ff6b00&textColor=ffffff",
    sector: "HealthTech",
    stage: "Seed",
    hq: "Chicago",
    founded: 2015,
    employees: "50-200",
    thesisScore: 80,
    tags: ["ai", "oncology", "genomics"],
    lastSignalDate: "2026-02-04",
    description: "AI-powered genomic insights for cancer treatment.",
    enriched: undefined,
    noteIds: [],
  },

  // B2B SaaS (4)
  {
    id: "co_017",
    name: "PostHog",
    url: "https://posthog.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=PostHog&backgroundColor=1d1d1d&textColor=ffffff",
    sector: "B2B SaaS",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2020,
    employees: "50-200",
    thesisScore: 85,
    tags: ["analytics", "open-source", "plg"],
    lastSignalDate: "2026-02-06",
    description: "Open-source product analytics platform for engineers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_018",
    name: "Cal.com",
    url: "https://cal.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Calcom&backgroundColor=111827&textColor=ffffff",
    sector: "B2B SaaS",
    stage: "Seed",
    hq: "San Francisco",
    founded: 2021,
    employees: "10-50",
    thesisScore: 82,
    tags: ["scheduling", "open-source", "calendar"],
    lastSignalDate: "2026-01-29",
    description: "Open-source scheduling infrastructure for teams.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_019",
    name: "Dub",
    url: "https://dub.co",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Dub&backgroundColor=000000&textColor=ffffff",
    sector: "B2B SaaS",
    stage: "Pre-seed",
    hq: "San Francisco",
    founded: 2022,
    employees: "1-10",
    thesisScore: 76,
    tags: ["url-shortener", "open-source", "plg"],
    lastSignalDate: "2026-01-15",
    description: "Link management and shortening for modern teams.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_020",
    name: "Segment",
    url: "https://segment.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Segment&backgroundColor=19c500&textColor=ffffff",
    sector: "B2B SaaS",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2011,
    employees: "200-500",
    thesisScore: 90,
    tags: ["cdp", "data", "enterprise"],
    lastSignalDate: "2026-02-13",
    description: "Customer data platform for enterprise marketing.",
    enriched: undefined,
    noteIds: [],
  },

  // Climate (3)
  {
    id: "co_021",
    name: "Watershed",
    url: "https://watershed.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Watershed&backgroundColor=4a5568&textColor=ffffff",
    sector: "Climate",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2020,
    employees: "50-200",
    thesisScore: 84,
    tags: ["carbon-accounting", "esg", "enterprise"],
    lastSignalDate: "2026-02-02",
    description: "Carbon accounting and emissions management software.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_022",
    name: "Carbonfact",
    url: "https://carbonfact.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Carbonfact&backgroundColor=2d5016&textColor=ffffff",
    sector: "Climate",
    stage: "Seed",
    hq: "London",
    founded: 2019,
    employees: "10-50",
    thesisScore: 77,
    tags: ["carbon-accounting", "data", "analytics"],
    lastSignalDate: "2026-01-18",
    description: "Carbon footprint calculation and reporting platform.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_023",
    name: "Normative",
    url: "https://normative.io",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Normative&backgroundColor=1b4332&textColor=ffffff",
    sector: "Climate",
    stage: "Pre-seed",
    hq: "Berlin",
    founded: 2021,
    employees: "10-50",
    thesisScore: 73,
    tags: ["emissions", "sustainability", "ai"],
    lastSignalDate: "2026-01-10",
    description: "AI-powered sustainability reporting for enterprises.",
    enriched: undefined,
    noteIds: [],
  },

  // Security (2)
  {
    id: "co_024",
    name: "1Password",
    url: "https://1password.com",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=1Password&backgroundColor=0066ff&textColor=ffffff",
    sector: "Security",
    stage: "Series B",
    hq: "Toronto",
    founded: 2006,
    employees: "200-500",
    thesisScore: 86,
    tags: ["password-manager", "security", "enterprise"],
    lastSignalDate: "2026-02-16",
    description: "Password management and identity security platform.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_025",
    name: "Snyk",
    url: "https://snyk.io",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=Snyk&backgroundColor=ff5500&textColor=ffffff",
    sector: "Security",
    stage: "Series A",
    hq: "London",
    founded: 2015,
    employees: "50-200",
    thesisScore: 83,
    tags: ["devsecops", "vulnerability", "developer-tools"],
    lastSignalDate: "2026-02-17",
    description: "Developer-first vulnerability scanning and remediation.",
    enriched: undefined,
    noteIds: [],
  },
];
