import { Company } from "@/lib/types";

export const COMPANIES: Company[] = [
  // AI Infra (4)
  {
    id: "co_001",
    name: "Meridian",
    url: "https://openai.com",
    logoUrl: "https://logo.clearbit.com/openai.com",
    sector: "AI Infra",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2018,
    employees: "200-500",
    thesisScore: 92,
    tags: ["llm", "api-first", "enterprise"],
    lastSignalDate: "2026-02-15",
    description: "Large language models and AI platform for enterprise applications.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_002",
    name: "Vaultex",
    url: "https://anthropic.com",
    logoUrl: "https://logo.clearbit.com/anthropic.com",
    sector: "AI Infra",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2021,
    employees: "50-200",
    thesisScore: 88,
    tags: ["ai-safety", "llm", "research"],
    lastSignalDate: "2026-02-10",
    description: "Constitutional AI and safe large language model development.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_003",
    name: "Helix",
    url: "https://mistral.ai",
    logoUrl: "https://logo.clearbit.com/mistral.ai",
    sector: "AI Infra",
    stage: "Seed",
    hq: "Paris",
    founded: 2023,
    employees: "10-50",
    thesisScore: 85,
    tags: ["llm", "open-source", "inference"],
    lastSignalDate: "2026-01-28",
    description: "Open-source large language models for efficient inference.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_004",
    name: "Nexus",
    url: "https://modal.com",
    logoUrl: "https://logo.clearbit.com/modal.com",
    sector: "AI Infra",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2021,
    employees: "10-50",
    thesisScore: 82,
    tags: ["serverless", "gpu", "inference"],
    lastSignalDate: "2026-02-05",
    description: "Serverless GPU compute platform for AI applications.",
    enriched: undefined,
    noteIds: [],
  },

  // DevTools (4)
  {
    id: "co_005",
    name: "Meridian Code",
    url: "https://linear.app",
    logoUrl: "https://logo.clearbit.com/linear.app",
    sector: "DevTools",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2019,
    employees: "50-200",
    thesisScore: 91,
    tags: ["issue-tracking", "api-first", "plg"],
    lastSignalDate: "2026-02-12",
    description: "Fast, beautiful issue tracking for modern software teams.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_006",
    name: "Casca",
    url: "https://clerk.com",
    logoUrl: "https://logo.clearbit.com/clerk.com",
    sector: "DevTools",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2020,
    employees: "50-200",
    thesisScore: 87,
    tags: ["auth", "sdk", "developer-tools"],
    lastSignalDate: "2026-02-08",
    description: "Authentication and user management platform for developers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_007",
    name: "Driftlog",
    url: "https://resend.com",
    logoUrl: "https://logo.clearbit.com/resend.com",
    sector: "DevTools",
    stage: "Seed",
    hq: "San Francisco",
    founded: 2022,
    employees: "10-50",
    thesisScore: 84,
    tags: ["email", "api", "developer-tools"],
    lastSignalDate: "2026-02-03",
    description: "Email API for developers with beautiful templates.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_008",
    name: "Pyrite",
    url: "https://infisical.com",
    logoUrl: "https://logo.clearbit.com/infisical.com",
    sector: "DevTools",
    stage: "Pre-seed",
    hq: "San Francisco",
    founded: 2023,
    employees: "1-10",
    thesisScore: 78,
    tags: ["secrets-management", "open-source", "security"],
    lastSignalDate: "2026-01-25",
    description: "Open-source secrets management platform for teams.",
    enriched: undefined,
    noteIds: [],
  },

  // FinTech (4)
  {
    id: "co_009",
    name: "Zenith",
    url: "https://stripe.com",
    logoUrl: "https://logo.clearbit.com/stripe.com",
    sector: "FinTech",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2019,
    employees: "200-500",
    thesisScore: 94,
    tags: ["payments", "api-first", "enterprise"],
    lastSignalDate: "2026-02-14",
    description: "Global payment processing and financial infrastructure.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_010",
    name: "Nexo",
    url: "https://wise.com",
    logoUrl: "https://logo.clearbit.com/wise.com",
    sector: "FinTech",
    stage: "Series A",
    hq: "London",
    founded: 2011,
    employees: "200-500",
    thesisScore: 89,
    tags: ["remittance", "payments", "cross-border"],
    lastSignalDate: "2026-02-09",
    description: "Fast, cheap international money transfers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_011",
    name: "Vault Finance",
    url: "https://checkout.com",
    logoUrl: "https://logo.clearbit.com/checkout.com",
    sector: "FinTech",
    stage: "Series A",
    hq: "London",
    founded: 2012,
    employees: "50-200",
    thesisScore: 86,
    tags: ["payments", "api", "merchants"],
    lastSignalDate: "2026-02-01",
    description: "Unified payment processing for online merchants.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_012",
    name: "Aurum",
    url: "https://plaid.com",
    logoUrl: "https://logo.clearbit.com/plaid.com",
    sector: "FinTech",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2013,
    employees: "50-200",
    thesisScore: 81,
    tags: ["banking-api", "data", "fintech"],
    lastSignalDate: "2026-01-30",
    description: "Bank connectivity API for financial applications.",
    enriched: undefined,
    noteIds: [],
  },

  // HealthTech (4)
  {
    id: "co_013",
    name: "Vitals",
    url: "https://ro.co",
    logoUrl: "https://logo.clearbit.com/ro.co",
    sector: "HealthTech",
    stage: "Series A",
    hq: "New York",
    founded: 2017,
    employees: "50-200",
    thesisScore: 83,
    tags: ["telehealth", "prescription", "plg"],
    lastSignalDate: "2026-02-11",
    description: "Telehealth and prescription delivery platform.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_014",
    name: "Asclepius",
    url: "https://flatiron.com",
    logoUrl: "https://logo.clearbit.com/flatiron.com",
    sector: "HealthTech",
    stage: "Series B",
    hq: "New York",
    founded: 2015,
    employees: "200-500",
    thesisScore: 88,
    tags: ["cancer", "software", "healthcare"],
    lastSignalDate: "2026-02-07",
    description: "Software platform for cancer treatment centers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_015",
    name: "MediFlow",
    url: "https://omada.com",
    logoUrl: "https://logo.clearbit.com/omada.com",
    sector: "HealthTech",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2017,
    employees: "200-500",
    thesisScore: 79,
    tags: ["chronic-disease", "digital-health", "b2b"],
    lastSignalDate: "2026-01-22",
    description: "Digital health platform for chronic disease management.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_016",
    name: "Precision",
    url: "https://tempus.com",
    logoUrl: "https://logo.clearbit.com/tempus.com",
    sector: "HealthTech",
    stage: "Seed",
    hq: "Chicago",
    founded: 2015,
    employees: "50-200",
    thesisScore: 80,
    tags: ["ai", "oncology", "genomics"],
    lastSignalDate: "2026-02-04",
    description: "AI-powered genomic insights for cancer treatment.",
    enriched: undefined,
    noteIds: [],
  },

  // B2B SaaS (4)
  {
    id: "co_017",
    name: "Insight Analytics",
    url: "https://posthog.com",
    logoUrl: "https://logo.clearbit.com/posthog.com",
    sector: "B2B SaaS",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2020,
    employees: "50-200",
    thesisScore: 85,
    tags: ["analytics", "open-source", "plg"],
    lastSignalDate: "2026-02-06",
    description: "Open-source product analytics platform for engineers.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_018",
    name: "Spectrum",
    url: "https://cal.com",
    logoUrl: "https://logo.clearbit.com/cal.com",
    sector: "B2B SaaS",
    stage: "Seed",
    hq: "San Francisco",
    founded: 2021,
    employees: "10-50",
    thesisScore: 82,
    tags: ["scheduling", "open-source", "calendar"],
    lastSignalDate: "2026-01-29",
    description: "Open-source scheduling infrastructure for teams.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_019",
    name: "Lumina",
    url: "https://dub.co",
    logoUrl: "https://logo.clearbit.com/dub.co",
    sector: "B2B SaaS",
    stage: "Pre-seed",
    hq: "San Francisco",
    founded: 2022,
    employees: "1-10",
    thesisScore: 76,
    tags: ["url-shortener", "open-source", "plg"],
    lastSignalDate: "2026-01-15",
    description: "Link management and shortening for modern teams.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_020",
    name: "Zenith Analytics",
    url: "https://segment.com",
    logoUrl: "https://logo.clearbit.com/segment.com",
    sector: "B2B SaaS",
    stage: "Series B",
    hq: "San Francisco",
    founded: 2011,
    employees: "200-500",
    thesisScore: 90,
    tags: ["cdp", "data", "enterprise"],
    lastSignalDate: "2026-02-13",
    description: "Customer data platform for enterprise marketing.",
    enriched: undefined,
    noteIds: [],
  },

  // Climate (3)
  {
    id: "co_021",
    name: "EcoTrack",
    url: "https://watershed.com",
    logoUrl: "https://logo.clearbit.com/watershed.com",
    sector: "Climate",
    stage: "Series A",
    hq: "San Francisco",
    founded: 2020,
    employees: "50-200",
    thesisScore: 84,
    tags: ["carbon-accounting", "esg", "enterprise"],
    lastSignalDate: "2026-02-02",
    description: "Carbon accounting and emissions management software.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_022",
    name: "Zenith Green",
    url: "https://carbonfact.com",
    logoUrl: "https://logo.clearbit.com/carbonfact.com",
    sector: "Climate",
    stage: "Seed",
    hq: "London",
    founded: 2019,
    employees: "10-50",
    thesisScore: 77,
    tags: ["carbon-accounting", "data", "analytics"],
    lastSignalDate: "2026-01-18",
    description: "Carbon footprint calculation and reporting platform.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_023",
    name: "Verdant",
    url: "https://normative.io",
    logoUrl: "https://logo.clearbit.com/normative.io",
    sector: "Climate",
    stage: "Pre-seed",
    hq: "Berlin",
    founded: 2021,
    employees: "10-50",
    thesisScore: 73,
    tags: ["emissions", "sustainability", "ai"],
    lastSignalDate: "2026-01-10",
    description: "AI-powered sustainability reporting for enterprises.",
    enriched: undefined,
    noteIds: [],
  },

  // Security (2)
  {
    id: "co_024",
    name: "Sentinel",
    url: "https://1password.com",
    logoUrl: "https://logo.clearbit.com/1password.com",
    sector: "Security",
    stage: "Series B",
    hq: "Toronto",
    founded: 2006,
    employees: "200-500",
    thesisScore: 86,
    tags: ["password-manager", "security", "enterprise"],
    lastSignalDate: "2026-02-16",
    description: "Password management and identity security platform.",
    enriched: undefined,
    noteIds: [],
  },
  {
    id: "co_025",
    name: "Vortex Security",
    url: "https://snyk.io",
    logoUrl: "https://logo.clearbit.com/snyk.io",
    sector: "Security",
    stage: "Series A",
    hq: "London",
    founded: 2015,
    employees: "50-200",
    thesisScore: 83,
    tags: ["devsecops", "vulnerability", "developer-tools"],
    lastSignalDate: "2026-02-17",
    description: "Developer-first vulnerability scanning and remediation.",
    enriched: undefined,
    noteIds: [],
  },
];
